package mx.com.ProyectoBasico.ConsultasGen.Esp.tecnm.ProyectoFinalConsultasGeneralesYEspecialidad.repositories

import mx.com.ProyectoBasico.ConsultasGen.Esp.tecnm.ProyectoFinalConsultasGeneralesYEspecialidad.Entity.PersonalMedicoEspecialidadSubespecialidad
import org.springframework.data.jpa.repository.JpaRepository
import java.util.*

interface PersonalMedicoEspecialidadSubespecialidadRepository : JpaRepository<PersonalMedicoEspecialidadSubespecialidad, UUID> {
}
